### ISSUE TITLE
Support for 88.2kHz and 176.4kHz

### ISSUE THREAD

**Issue by PureLin** [kiffie/rpi-i2s-spdif#2]
Hi, this project is amazing, good job!
I am curious why don't support these sample rate, the original I2S output is support it.
I tried to add them into the configs code and install it, but seems not work.

**Comment by PureLin** [comment]
Sorry my fault, forget to remove the previous install, adding config will works perfect.

**Comment by kiffie** [comment]
Great to hear that it works
