### ISSUE TITLE
Electrical transmitter connection

### ISSUE THREAD

**Issue by agg23** [kiffie/rpi-i2s-spdif#3]
Other than the RPi 1's composite video connector, have you attempted electrical transmission of a S/PDIF signal? Did you just do a straight connection to the center pin on the RCA connector and a ground?

I'm attempting to replicate your results on a RPi 3b+, but have been unable to get my DAC to recognize the signal. I have not looked at the signal in an oscilloscope though.

**Comment by kiffie** [comment]
Hi,

I connected pin 40 (GPIO 21) via a 100 nF capacitor to the center pin of the RCA connector. You can also try a TOSLINK transmitter like Cliff FCR684208T.

If you want to test the output and you do not have a oscilloscope, you can connect a low current (2 mA) LED via a 470 Ohms resistor to pin 40. When outputting sound, the LED should illuminate. The LED should be brighter when connected via the resistor to 3.3 V instead to pin 40.

I successfully tried the electrical connection on a Raspberry Pi 3 Model B Rev 1.2.

**Comment by agg23** [comment]
On RPi 3 (or really anything not RPi 1), do you need any passive components inline with the electrical connection? Is the 75 ohm impedance covered by the sink (so the DAC)?

**Comment by kiffie** [comment]
The only component I used in my experimental setup is the 100 nF capacitor for blocking DC. There is no impedance matching. This is of course not a perfect transmitter but it works for me. Correctly implemented electrical transmitters have a transformer or the like.

**Comment by agg23** [comment]
I got it working with a 330 ohm resistor in series with the center pin. No capacitor. Pin 40 - 330 ohm - RCA center pin.

I was very surprised to find it started playing back without a common ground provided.

**Comment by kiffie** [comment]
That is indeed surprising. I always connected the grounds of the two devices.
