### ISSUE TITLE
Continuous S/PDIF output

### ISSUE THREAD

**Issue by agg23** [kiffie/rpi-i2s-spdif#4]
In #1 you state:
> The SPDIF signal is on GPIO 21 only while playing. The 5.6448 MHz clock is continuously available at GPIO 18. For my tests, I connected an optical transmitter to GPIO 21.

Is there a simple way to make the signal continuously available? I don't want there to be a signal acquisition delay when changing sources or sample rates. Additionally, my DAC turns off when there is no signal.

**Comment by kiffie** [comment]
Basically, the driver must be so modified that it outputs a silent (zero samples) SPDIF signal when there is no ALSA output.

**Comment by kiffie** [comment]
BTW, not clear to me how a "good" SPDIF output should behave when there is no audio stream. Maybe, simply removing the signal is already the correct implementation?

**Comment by agg23** [comment]
I'm not sure. My optical S/PDIF output from my Windows PC constantly keeps my DAC active when there's no audio output whatsoever, so that's what I'd like to achieve. I think it makes sense that the devices remain in communication, even if there's no data to send at this time.

**Comment by kiffie** [comment]
I tried the same on a Intel mainboard with SPDIF output under Linux. Here, the SPDIF signal was interrupted when not playing.

Nevertheless, I put a modified version of the driver in the branch `continuous_signal`. Feel free to test it.

**Comment by mbeijen** [comment]
Hi, I’m not sure but this page points out it might be common to use the ‘validity bit’, bit 28 for this: https://en.m.wikipedia.org/wiki/AES3

> It is used by most CD players to indicate that concealment rather than error correction is taking place.

**Comment by kiffie** [comment]
Currently, zero samples are sent when there is no audio stream but the validity bit is not changed. This works very well. Not sure if setting the validity bit makes sense (but would be easy to implement).

**Comment by agg23** [comment]
That's great, thanks. I have yet to try it (my setup somehow broke itself), but I really appreciate it.

**Comment by agg23** [comment]
Just wanted to say thank you again. Finally got to try it and it works perfectly. I really appreciate how quickly you implemented this.

**Comment by kiffie** [comment]
> Just wanted to say thank you again. Finally got to try it and it works perfectly. I really appreciate how quickly you implemented this.

No problem. It was fun to work on this small kernel module once again.
